version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: flask-backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/app.db:/app/app.db
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "5173:80"  
    restart: always
    depends_on:
      - backend
